name: untitled
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  cupertino_icons: ^1.0.2
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  provider: ^6.0.2
  connectivity_plus: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

